# Form implementation generated from reading ui file '/Users/thaiha/PycharmProjects/PythonProject/ex73/ui/MyMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(428, 254)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.heSoALabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.heSoALabel.setObjectName("heSoALabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.heSoALabel)
        self.heSoALineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.heSoALineEdit.setObjectName("heSoALineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.heSoALineEdit)
        self.heSoBLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.heSoBLabel.setObjectName("heSoBLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.heSoBLabel)
        self.heSoBLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.heSoBLineEdit.setObjectName("heSoBLineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.heSoBLineEdit)
        self.heSoCLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.heSoCLabel.setObjectName("heSoCLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.heSoCLabel)
        self.heSoCLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.heSoCLineEdit.setObjectName("heSoCLineEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.heSoCLineEdit)
        self.ketQuaLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.ketQuaLabel.setObjectName("ketQuaLabel")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.ketQuaLabel)
        self.ketQuaLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ketQuaLineEdit.setObjectName("ketQuaLineEdit")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.ketQuaLineEdit)
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.pushButton)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 428, 29))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Phuong trinh bac 2"))
        self.heSoALabel.setText(_translate("MainWindow", "He so a: "))
        self.heSoBLabel.setText(_translate("MainWindow", "He so b:"))
        self.heSoCLabel.setText(_translate("MainWindow", "He so c:"))
        self.ketQuaLabel.setText(_translate("MainWindow", "Ket qua:"))
        self.pushButton.setText(_translate("MainWindow", "Calculate"))
